var quotes = [
    "\"To become great sometimes you have to start small.\"  <br>  <em> -Gbenga",
    "\"knowing your boundaries in people\'s life gives you peace of mind.\" <br> <em>-Gbenga",
    "\"One good turn deserve another.\"   <br> <em> -Gbenga",
    "\"When you have a dream, you’ve got to grab it and never let go.\" <br> <em> - Carol Burnet",
    "\"Nothing is impossible. The word itself says ‘I’m possible!\" <br> <em>  -Audrey Hepburn",
    "\"There is nothing impossible to they who will try.\" <br> <em> -Alexander the Great ",
    "\"The bad news is time flies. The good news is you’re the pilot.\" <br> <em>  -Michael Altshuler",
    "\"Life has got all those twists and turns. You’ve got to hold on tight and off you go.\" <br><em>—Nicole Kidman",
    "\"Keep your face always toward the sunshine, and shadows will fall behind you\" <br> <em> -Walt Whitman",                        
    "\"Success is not final, failure is not fatal: it is the courage to continue that counts\" <br> <em>– Winston Churchill", 
    "\"You define your own life. Don’t let other people write your script\" <br> <em>-Oprah Winfrey", 
    "\"You are never too old to set another goal or to dream a new dream.\" <br> <em>—Malala Yousafzai", 
    "\"Spread love everywhere you go\" <br> <em>—Mother Teresa", 
    "\"You don’t always need a plan. Sometimes you just need to breathe, trust, let go and see what happens\" <br> <em>  -Mandy Hale", 
    "\"You can be everything. You can be the infinite amount of things that people are\" <br> <em>  -Kesha", 
    "\"What lies behind you and what lies in front of you, pales in comparison to what lies inside of you\" <br> <em>  -Ralph Waldo Emerson", 
    "\"Belief creates the actual fact\" <br> <em>  -William James", 
    "\"No matter what people tell you, words and ideas can change the world.\" <br> <em>-Robin Williams", 
    "\"It is during our darkest moments that we must focus to see the light.\" <br> <em>  -Aristotle", 
    "\"Believe you can and you’re halfway there.\" <br> <em>  -Theodore Roosevelt", 
    "\"Weaknesses are just strengths in the wrong environment.\" <br> <em>  -Marianne Cantwell", 
    "\"In a gentle way, you can shake the world.\" <br> <em>  -— Mahatma Gandhi", 
    "\"Try to be a rainbow in someone’s cloud\" <br> <em>  -— Maya Angelou", 
    "\"Real change, enduring change, happens one step at a time.\" <br> <em>  -— Ruth Bader Ginsburg", 
    "\"Wake up determined, go to bed satisfied.\" <br> <em>  -Dwayne", 
    "\"Life is like riding a bicycle. To keep your balance, you must keep moving.\" <br> <em>  -– Albert Einstein", 
    "\"Faith is love taking the form of aspiration.\" <br> <em>  -—William Ellery Channing", 
    "\"If you don’t like the road you’re walking, start paving another one\" <br> <em>  -— Dolly Parton", 
    "\"We generate fears while we sit. We overcome them by action.\" <br> <em>  -— Dr. Henry Link", 
    "\"Out of the mountain of despair, a stone of hope.\" <br> <em>  — Martin Luther King, Jr.-", 
    "\"The only limit to our realization of tomorrow will be our doubts today.\" <br> <em>  -— Franklin Delano Roosevelt", 
    "\"It is never too late to be what you might have been.\" <br> <em>  -George Eliot", 
    "\"Find that inner joy and express it, you don't have to be rich to create your own happiness.\" <br> <em>  -Gbenga", 
    "\"You do not find the happy life. You make it.\" <br> <em>  -Camilla Eyring Kimball",  
    "\"We all have problems. But it’s not what happens to us, [it’s] the choices we make after.\" <br> <em>  -Elizabeth Smart", 
    "\"When we let fear be our master, we cannot be happy and free as a butterfly\" <br> <em>  -Annicken R. Day", 
    "\"You must find the place inside yourself where nothing is impossible.\" <br> <em>  -Deepak Chopra", 
    "\"A lot of people are afraid to say what they want. That’s why they don’t get what they want.\" <br> <em>  -Madonna", 
    "\"In order for the light to shine so brightly, the darkness must be present.\" <br> <em>  -Sir Francis Bacon", 
    "\"Never bend your head. Always hold it high. Look the world straight in the eye.\" <br> <em>  -Helen Keller", 
    "\"If my mind can conceive it, if my heart can believe it, then I can achieve it.\" <br> <em>  -Muhammad Ali", 
    "\"If you want to achieve greatness stop asking for permission.\" <br> <em>  -Anonymous", 
    "\"To live a creative life, we must lose our fear of being wrong.\" <br> <em>  -Anonymous", 
    "\"If you are not willing to risk the usual you will have to settle for the ordinary.\" <br> <em>  -Jim Rohn", 
    "\"Trust because you are willing to accept the risk, not because it's safe or certain\" <br> <em>  -Anonymous", 
    "\"All our dreams can come true if we have the courage to pursue them.\" <br> <em>  -Walt Disney", 
    "\"Good things come to people who wait, but better things come to those who go out and get them.\" <br> <em>  -Anonymous", 
    "\"Success is walking from failure to failure with no loss of enthusiasm.\" <br> <em>  --Winston Churchill", 
    "\"Just when the caterpillar thought the world was ending, he turned into a butterfly.\" <br> <em>  --Proverb", 
    "\"Opportunities don't happen, you create them.\" <br> <em>  -Chris Grosser", 
    "\"Try not to become a person of success, but rather try to become a person of value\" <br> <em>  -Albert Einstein", 
    "\"Great minds discuss ideas; average minds discuss events; small minds discuss people.\" <br> <em>  -Eleanor Roosevelt", 
    "\"I have not failed. I've just found 10,000 ways that won't work.\" <br> <em>  -Thomas A. Edison", 
    "\"If you don't value your time, neither will others. Stop giving away your time and talents--start charging for it.\" <br> <em>  -Kim Garst", 
    "\"A successful man is one who can lay a firm foundation with the bricks others have thrown at him.\" <br> <em>  -David Brinkley", 
    "\"No one can make you feel inferior without your consent.\" <br> <em>  -Eleanor Roosevelt", 
    "\"The whole secret of a successful life is to find out what is one's destiny to do, and then do it.\" <br> <em>  -Henry Ford", 
    "\"Don't raise your voice, improve your argument.\" <br> <em>  -Anonymous", 
    "\"What seems to us as bitter trials are often blessings in disguise.\" <br> <em>  -Oscar Wilde", 
    "\"When you stop chasing the wrong things, you give the right things a chance to catch you.\" <br> <em>  -Lolly Daskal", 
    "\"I believe that the only courage anybody ever needs is the courage to follow your own dreams.\" <br> <em>  -Oprah Winfrey", 
    "\"No masterpiece was ever created by a lazy artist.\" <br> <em>  -Anonymous", 
    "\"Blessed are those who can give without remembering and take without forgetting.\" <br> <em>  -Anonymous", 
    "\"Do one thing every day that scares you.\" <br> <em>  -Anonymous", 
    "\"Your problem isn't the problem. Your reaction is the problem.\" <br> <em>  --Anonymous", 
    "\"You can do anything, but not everything.\" <br> <em>  -Anonymous", 
    "\"Innovation distinguishes between a leader and a follower.\" <br> <em> -Steve Jobs ", 
    "\"There are two types of people who will tell you that you cannot make a difference in this world: those who are afraid to try and those who are afraid you will succeed.\" <br> <em>  -Ray Goforth", 
    "\"I find that the harder I work, the more luck I seem to have.\" <br> <em>  -Thomas Jefferson", 
    "\"The starting point of all achievement is desire.\" <br> <em> -Napoleon Hill ", 
    "\"Success is the sum of small efforts, repeated day-in and day-out.\" <br> <em>  -Robert Collier", 
    "\"All progress takes place outside the comfort zone.\" <br> <em>  -Michael John Bobak", 
    "\"You may only succeed if you desire succeeding; you may only fail if you do not mind failing.\" <br> <em>  -Philippos", 
    "\"Courage is resistance to fear, mastery of fear--not absence of fear.\" <br> <em>  -Mark Twain", 
    "\"We become what we think about most of the time, and that's the strangest secret.\" <br> <em>  -Earl Nightingale", 
    "\"The only place where success comes before work is in the dictionary.\" <br> <em>  -Vidal Sassoon", 
    "\"Too many of us are not living our dreams because we are living our fears.\" <br> <em> -Les Brown ", 
    "\"It's not what you look at that matters, it's what you see.\" <br> <em>  -Anonymous", 
    "\"The road to success and the road to failure are almost exactly the same.\" <br> <em> -Colin R. Davis ", 
    "\"The function of leadership is to produce more leaders, not more followers.\" <br> <em>  -Ralph Nader", 
    "\"Success is liking yourself, liking what you do, and liking how you do it.\" <br> <em> -Maya Angelou ", 
    "\"As we look ahead into the next century, leaders will be those who empower others.\" <br> <em>  -Bill Gates", 
    "\"The successful warrior is the average man, with laser-like focus.\" <br> <em>  -Bruce Lee", 
    "\"There is no traffic jam along the extra mile.\" <br> <em> -Roger Staubach ", 
    "\"Develop success from failures. Discouragement and failure are two of the surest stepping stones to success.\" <br> <em>  -Dale Carnegie", 
    "\"If you don't design your own life plan, chances are you'll fall into someone else's plan. And guess what they have planned for you? Not much.\" <br> <em>  -Jim Rohn", 
    "\"If you genuinely want something, don't wait for it--teach yourself to be impatient.\" <br> <em> -Gurbaksh Chahal  ", 
    "\"Don't let the fear of losing be greater than the excitement of winning.\" <br> <em>  -Robert Kiyosaki", 
    "\"If you want to make a permanent change, stop focusing on the size of your problems and start focusing on the size of you!\" <br> <em>  -T. Harv Eker", 
    "\"The number one reason people fail in life is because they listen to their friends, family, and neighbors.\" <br> <em>  -Napoleon Hill", 
    "\"Success does not consist in never making mistakes but in never making the same one a second time.\" <br> <em> -George Bernard Shaw ", 
    "\"You must expect great things of yourself before you can do them.\" <br> <em>  -Michael Jordan", 
    "\"Motivation is what gets you started. Habit is what keeps you going.\" <br> <em>-Jim Ryun  ", 
    "\"People rarely succeed unless they have fun in what they are doing\" <br> <em> -Dale Carnegie ", 
    "\"Be miserable. Or motivate yourself. Whatever has to be done, it's always your choice.\" <br> <em> -Wayne Dyer ", 
    "\"To accomplish great things, we must not only act, but also dream, not only plan, but also believe.\" <br> <em>  -Anatole France", 
    "\"Most of the important things in the world have been accomplished by people who have kept on trying when there seemed to be no help at all.\" <br> <em>  -Dale Carnegie", 
    "\"It is better to fail in originality than to succeed in imitation.\" <br> <em> -Herman Melville ", 
    "\"You may have to fight a battle more than once to win it.\" <br> <em>  -Margaret Thatcher", 
]

function newQuote() {
var randomNumber = Math.floor(Math.random() * (quotes.length));
document.getElementById('quoteDisplay').innerHTML = quotes[randomNumber];
}